name: pgen
version: '1.0.0'
base: core18
summary: Provides applications for reading quran and hadith # 79 char long summary
description: |
  sna-description

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  pgen:
    command: desktop-launch pgenstart
    plugs: [desktop, desktop-legacy, x11, unity7, wayland, opengl]
#    desktop: /usr/share/applications/pgen.desktop

parts:
  desktop-gui:
    plugin: dump
    source: src/
    organize:
      "pgenstart": "bin/pgenstart"
#      "pgen.png": "bin/pgen.png"
#      "gui.ui": "bin/gui.ui"
#      "data/pgen.desktop": /usr/share/applications/pgen.desktop
#     "data/pgen.png": /usr/share/applications/pgen.png

    stage-packages:
    - libdouble-conversion1
    - libdrm2
    - libegl1
    - libfontconfig1
    - libfreetype6
    - libgbm1
    - libgl1
    - libglvnd0
    - libglx0
    - libgraphite2-3
    - libharfbuzz0b
    - libice6
    - libicu60
    - libjpeg-turbo8
    - libpng16-16
    - libsm6
    - libwayland-server0
    - libx11-6
    - libx11-xcb1
    - libxau6
    - libxcb-glx0
    - libxcb-xkb1
    - libxcb1
    - libxdmcp6
    - libxkbcommon-x11-0
    - libxkbcommon0
    - libxrender1
    after: [desktop-qt5]

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5
